### ISSUE TITLE
Memory leak in identify -help

### ISSUE THREAD

**Issue by luisfrod** [ImageMagick/ImageMagick6#113]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

 ```
==16466==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16792 byte(s) in 1 object(s) allocated from:
    #0 0x493aad in malloc (/usr/local/bin/identify+0x493aad)
    #1 0x7f0e8304a0d5 in AcquireMagickMemory magick/memory.c:531:10
    #2 0x7f0e83016680 in AcquireImageInfo magick/image.c:316:28
    #3 0x7f0e8301c258 in CloneImageInfo magick/image.c:928:14
    #4 0x7f0e82afc56f in IdentifyImageCommand wand/identify.c:252:3
    #5 0x7f0e82b403bb in MagickCommandGenesis wand/mogrify.c:173:14
    #6 0x4c32ac in IdentifyMain utilities/identify.c:80:10
    #7 0x4c31a8 in main utilities/identify.c:93:10
    #8 0x7f0e821a70b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x493aad in malloc (/usr/local/bin/identify+0x493aad)
    #1 0x7f0e8304a0d5 in AcquireMagickMemory magick/memory.c:531:10
    #2 0x7f0e8304a2f0 in AcquireQuantumMemory magick/memory.c:649:10
    #3 0x7f0e8317a8fe in ExpandFilenames magick/utility.c:768:20
    #4 0x7f0e82afc5c4 in IdentifyImageCommand wand/identify.c:261:10
    #5 0x7f0e82b403bb in MagickCommandGenesis wand/mogrify.c:173:14
    #6 0x4c32ac in IdentifyMain utilities/identify.c:80:10
    #7 0x4c31a8 in main utilities/identify.c:93:10
    #8 0x7f0e821a70b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Indirect leak of 15 byte(s) in 2 object(s) allocated from:
    #0 0x493aad in malloc (/usr/local/bin/identify+0x493aad)
    #1 0x7f0e8304a0d5 in AcquireMagickMemory magick/memory.c:531:10
    #2 0x7f0e8304a2f0 in AcquireQuantumMemory magick/memory.c:649:10
    #3 0x7f0e8314a0d0 in ConstantString magick/string.c:711:26
    #4 0x7f0e8317ab6d in ExpandFilenames magick/utility.c:796:21
    #5 0x7f0e82afc5c4 in IdentifyImageCommand wand/identify.c:261:10
    #6 0x7f0e82b403bb in MagickCommandGenesis wand/mogrify.c:173:14
    #7 0x4c32ac in IdentifyMain utilities/identify.c:80:10
    #8 0x4c31a8 in main utilities/identify.c:93:10
    #9 0x7f0e821a70b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: 16831 byte(s) leaked in 4 allocation(s).
```

### Steps to Reproduce
Just the help argument of the identify command:
 ```
identify -help
```

### System Configuration

- ImageMagick version:  ImageMagick 6.9.11-44 Q16 x86_64
- Environment (Operating system, version and so on): Ubuntu 20.04.1 LTS (GNU/Linux 4.4.0-19041-Microsoft x86_64)
- Additional information: ./configure CC="clang" CFLAGS="-fsanitize=address -O1 -fno-omit-frame-pointer -g"

**Comment by TheCrott** [comment]
I've found this issue around 2 months ago, but what's the severity of this issue?

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
