### ISSUE TITLE
convert foo.jpg json: aborts with 6.9.12-58

### ISSUE THREAD

**Issue by mtasaka** [ImageMagick/ImageMagick6#191]
### ImageMagick version

6.9.12-58

### Operating system

Linux

### Operating system, version and so on

Fedora 37 x86_64

### Description

With ImageMagick 6.9.12-58, executing `convert foo.jpg json:` aborts like below.
6.9.12-52 is okay, no problem.

```
[mockbuild@d30a52ed43484a2580c759652a82e649 test]$ gdb --args convert test.jpg json:
GNU gdb (GDB) Fedora 12.1-3.fc37

Reading symbols from convert...
Reading symbols from /usr/lib/debug/usr/bin/convert-6.9.12.58-1.fc37.x86_64.debug...
(gdb) r
Starting program: /usr/bin/convert test.jpg json:
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff6be46c0 (LWP 247)]
[New Thread 0x7ffff63e36c0 (LWP 248)]
[New Thread 0x7ffff5be26c0 (LWP 249)]
[New Thread 0x7ffff53e16c0 (LWP 250)]
[New Thread 0x7ffff4be06c0 (LWP 251)]
[{
  "version": "1.0",
  "image": {
    "name": "test.jpg",
    "format": "JPEG",
    "formatDescription": "Joint Photographic Experts Group JFIF format",
    "mimeType": "image/jpeg",
    "class": "DirectClass",
    "geometry": {
      "width": 800,
      "height": 488,
      "x": 0,
      "y": 0
    },
    "resolution": {
      "x": 72,
      "y": 72
    },
    "printSize": {
      "x": 11.1111,
      "y": 6.77778
    },
    "units": "PixelsPerInch",
    "type": "TrueColor",
    "endianness": "Undefined",
    "colorspace": "sRGB",
    "depth": 8,
    "baseDepth": 8,
    "channelDepth": {
      "red": 8,
      "green": 8,
      "blue": 8
    },
    "pixels": 390400,
    "imageStatistics": {
      "all": {
        "min": 0,
        "max": 255,
        "mean": 223.254,
        "standardDeviation": 32.3461,
        "kurtosis": 21.4981,
        "skewness": -4.45973,
        "entropy": 0.37879
      }
    },
    "channelStatistics": {
      "red": {
        "min": 0,
        "max": 255,
        "mean": 223.253,
 convert: coders/json.c:327: ColorFormatLocaleFile: Assertion `index != (const IndexPacket *) NULL' failed.

Thread 1 "convert" received signal SIGABRT, Aborted.
0x00007ffff7984adc in __pthread_kill_implementation () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install bzip2-libs-1.0.8-11.fc36.x86_64 fontconfig-2.14.0-1.fc37.x86_64 freetype-2.12.1-2.fc37.x86_64 fribidi-1.0.12-1.fc37.x86_64 glib2-2.73.1-2.fc37.x86_64 glibc-2.35.9000-29.fc37.x86_64 graphite2-1.3.14-9.fc36.x86_64 harfbuzz-4.4.1-1.fc37.x86_64 lcms2-2.13.1-1.fc37.x86_64 libICE-1.0.10-8.fc36.x86_64 libSM-1.2.3-10.fc36.x86_64 libX11-1.8.1-1.fc37.x86_64 libXext-1.3.4-8.fc36.x86_64 libXt-1.2.1-2.fc36.x86_64 libbrotli-1.0.9-8.fc37.x86_64 libgcc-12.1.1-3.fc37.x86_64 libgomp-12.1.1-3.fc37.x86_64 libjpeg-turbo-2.1.3-1.fc37.x86_64 liblqr-1-0.4.2-19.fc36.x86_64 libpng-1.6.37-12.fc36.x86_64 libraqm-0.8.0-1.fc36.x86_64 libtool-ltdl-2.4.7-1.fc37.x86_64 libuuid-2.38-4.fc37.x86_64 libxcb-1.13.1-9.fc36.x86_64 libxml2-2.9.14-2.fc37.x86_64 pcre-8.45-1.fc36.1.x86_64 xz-libs-5.2.5-9.fc37.x86_64 zlib-1.2.12-3.fc37.x86_64
(gdb) bt
#0  0x00007ffff7984adc in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff7934ae6 in raise () from /lib64/libc.so.6
#2  0x00007ffff791e7fc in abort () from /lib64/libc.so.6
#3  0x00007ffff791e71b in __assert_fail_base.cold () from /lib64/libc.so.6
#4  0x00007ffff792d696 in __assert_fail () from /lib64/libc.so.6
#5  0x00007ffff6bea321 in ColorFormatLocaleFile (index=<optimized out>, p=<optimized out>, image=<optimized out>, format=<optimized out>, file=<optimized out>) at coders/json.c:327
#6  EncodeImageAttributes (image=image@entry=0x555555580190, file=0x7ffff7acb780 <_IO_2_1_stdout_>) at coders/json.c:1438
#7  0x00007ffff6beb316 in WriteJSONImage (image_info=0x555555585700, image=<optimized out>) at coders/json.c:1786
#8  0x00007ffff7c90e61 in WriteImage (image_info=image_info@entry=0x55555556b930, image=image@entry=0x555555580190) at magick/constitute.c:1316
#9  0x00007ffff7c91866 in WriteImages (image_info=image_info@entry=0x555555567790, images=<optimized out>, images@entry=0x555555580190, filename=filename@entry=0x555555561d20 "json:", 
    exception=exception@entry=0x55555555edd0) at magick/constitute.c:1469
#10 0x00007ffff7b1233b in ConvertImageCommand (image_info=0x555555567790, image_info@entry=0x5555555635f0, argc=<optimized out>, argc@entry=3, argv=<optimized out>, argv@entry=0x7fffffffe498, metadata=metadata@entry=0x0, 
    exception=exception@entry=0x55555555edd0) at wand/convert.c:3234
#11 0x00007ffff7b7af21 in MagickCommandGenesis (image_info=image_info@entry=0x5555555635f0, command=0x7ffff7b12140 <ConvertImageCommand>, argc=argc@entry=3, argv=argv@entry=0x7fffffffe498, metadata=metadata@entry=0x0, 
    exception=exception@entry=0x55555555edd0) at wand/mogrify.c:173
#12 0x00005555555551c1 in ConvertMain (argv=0x7fffffffe498, argc=3) at utilities/convert.c:82
#13 main (argc=3, argv=0x7fffffffe498) at utilities/convert.c:94
```

I think the culprit is https://github.com/ImageMagick/ImageMagick6/commit/909d77066640baf07e01932b6aa5c719c50f1ccd
I think the above commit is unneeded and should be reverted:
`ColorFormatLocaleFile` calls `SetMagickPixelPacket` at
https://github.com/ImageMagick/ImageMagick6/blob/daae430bb05ec03b91bedaecf069d6ec561a339b/coders/json.c#L329 using `index`,
and in `SetMagickPixelPacket` , the case where `index` is NULL seems properly handled:
https://github.com/ImageMagick/ImageMagick6/blob/daae430bb05ec03b91bedaecf069d6ec561a339b/magick/pixel-private.h#L110-L111

### Steps to Reproduce

See above

### Images

![test](https://user-images.githubusercontent.com/403024/178995967-7117b93c-48ac-41fa-a549-757123115360.jpg)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
