### ISSUE TITLE
Uncaught ImagickException: insufficient image data in file `/tmp/magick-6363Yc7cfwZA0Drh

### ISSUE THREAD

**Issue by kdgeorgiev** [ImageMagick/ImageMagick6#232]
### ImageMagick version

6.9.7

### Operating system

Linux

### Operating system, version and so on

CentOS7

### Description

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.2
Active theme: TheGem (version 5.7.2)
Current plugin:  (version )
PHP version 7.4.33

```
Error Details
=============
An error of type E_ERROR was caused in line 39 of the file /home/troshevadm/public_html/wp-content/themes/thegem-elementor/inc/image-generator/image-editor.class.php. Error message: Uncaught ImagickException: insufficient image data in file `/tmp/magick-6363Yc7cfwZA0Drh' @ error/jpeg.c/ReadJPEGImage/1156 in /home/troshevadm/public_html/wp-content/themes/thegem-elementor/inc/image-generator/image-editor.class.php:39
Stack trace:
#0 /home/troshevadm/public_html/wp-content/themes/thegem-elementor/inc/image-generator/image-editor.class.php(39): Imagick->__construct('s3eucentral1://...')
ImageMagick/ImageMagick#1 /home/troshevadm/public_html/wp-content/themes/thegem-elementor/inc/image-generator/image-generator.php(70): TheGem_Dummy_WP_Image_Editor->get_size()
ImageMagick/ImageMagick#2 /home/troshevadm/public_html/wp-content/themes/thegem-elementor/inc/image-generator/image-generator.php(63): thegem_build_image_data('s3eucentral1://...')
ImageMagick/ImageMagick#3 /home/troshevadm/public_html/wp-content/themes/thegem-elementor/inc/image-generator/image-generator.php(26): thegem_get_thumbnail_src(196, 'thegem-gallery-...')
ImageMagick/ImageMagick#4 /home/troshevadm/public_html/wp-content/plugins/thegem-elements-elementor/thegem-elements-elementor.php(288): thegem_generate_thumbnail_sr
```

### Steps to Reproduce

No idea how I got it.

**Comment by kdgeorgiev** [comment]
Duplicate as the one above. It has better explanation and screenshots.
