### ISSUE TITLE
Segmentation fault inside ProfileImage

### ISSUE THREAD

**Issue by dlemstra** [ImageMagick/ImageMagick6#41]
New tests are being added to the https://github.com/rmagick/rmagick/ project and one of these tests discovered an issue inside the ProfileImage method in ImageMagick 6 (cannot be reproduced in ImageMagick 7). This issue can be reproduce by cloning the rmagick repository and running the following command: `convert doc/ex/images/Button_0.gif[0] -profile test/cmyk.icm -profile test/srgb.icm`. Below is the output of gdb (inside an ubuntu docker container with ImageMagick 6.9.10-39):

```
root@c8c88a53272f:/rmagick# gdb --args /ImageMagick-6.9.10-39/utilities/.libs/convert doc/ex/images/Button_0.gif[0] -profile test/cmyk.icm -profile test/srgb.icm null:
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /ImageMagick-6.9.10-39/utilities/.libs/convert...done.
(gdb) r
Starting program: /ImageMagick-6.9.10-39/utilities/.libs/convert doc/ex/images/Button_0.gif\[0\] -profile test/cmyk.icm -profile test/srgb.icm null:
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
ProfileImage._omp_fn.0 () at magick/profile.c:1179
1179                      *p++=LCMSScaleSource(GetPixelIndex(indexes+x));
(gdb) bt
#0  ProfileImage._omp_fn.0 () at magick/profile.c:1179
#1  0x00007ffff4fbdcff in GOMP_parallel () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff788b005 in ProfileImage (image=0x555555787e70, name=name@entry=0x5555557a2af0 "icc", datum=<optimized out>, length=length@entry=3144,
    magick_unused_clone=magick_unused_clone@entry=MagickFalse) at magick/profile.c:1136
#3  0x00007ffff7488aa9 in MogrifyImage (image_info=image_info@entry=0x55555576e5f0, argc=argc@entry=5, argv=argv@entry=0x555555772798, image=image@entry=0x7fffffffd0f8,
    exception=exception@entry=0x555555768dd0) at wand/mogrify.c:2521
#4  0x00007ffff7490539 in MogrifyImages (image_info=0x55555576e5f0, post=post@entry=MagickTrue, argc=5, argv=0x555555772798, images=images@entry=0x7fffffffd0f8,
    exception=exception@entry=0x555555768dd0) at wand/mogrify.c:8928
#5  0x00007ffff741ac3f in ConvertImageCommand (image_info=0x55555576e5f0, image_info@entry=0x55555576a450, argc=<optimized out>, argc@entry=7, argv=<optimized out>,
    argv@entry=0x7fffffffeb58, metadata=metadata@entry=0x0, exception=exception@entry=0x555555768dd0) at wand/convert.c:3256
#6  0x00007ffff7485456 in MagickCommandGenesis (image_info=0x55555576a450, command=0x7ffff7418700 <ConvertImageCommand>, argc=7, argv=0x7fffffffeb58, metadata=<optimized out>,
    exception=0x555555768dd0) at wand/mogrify.c:172
#7  0x00005555555549e9 in ConvertMain (argv=0x7fffffffeb58, argc=7) at utilities/convert.c:81
#8  main (argc=7, argv=0x7fffffffeb58) at utilities/convert.c:92
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by mockdeep** [comment]
Can this issue be closed now?
